### ISSUE TITLE
Gravity grenade

### ISSUE THREAD

**Issue by Kailo97** [ceLoFaN/hidenseek-csgo#33]
description: Then explode chgange gravity in detonate zone or block jump ability

implementation: if it 2nd type, just block +jump cmd. if it 1st, create spherical entity. I saw entity type like physics area, or just change players gravity (may be lower or bigger) and check they coords: comporate how far they from center coords and do effect timer.

**Comment by ceLoFaN** [comment]
I'm not sure if it is a good idea to add such grenades into the HNS plugin. I think it belongs in a different plugin.
