### ISSUE TITLE
hi ceLoFan. this a prophunt ?

### ISSUE THREAD

**Issue by nguyenbaodanh** [ceLoFaN/hidenseek-csgo#41]
Hello !
This mod is prophunt right ?

**Comment by ceLoFaN** [comment]
Hi there! It's not actually, sorry. It's the classic CS 1.6 HNS mod.
I should've made it clearer in the AlliedMods thread.

**Comment by ceLoFaN** [comment]
As far as I know [Zipcore] (https://github.com/Zipcore) used to have a repository of it. He might have deleted it or made it private.
