### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by jffz** [ceLoFaN/hidenseek-csgo#68]
Hi,

I'm rly interested to try out this mod but i have an issue when trying to compile (sm 1.6 and 1.8)

https://gyazo.com/418c66c304abdfa1cd4cd737e64a7e8b

**Comment by Kailo97** [comment]
WIll see tomorrow.

**Comment by ceLoFaN** [comment]
This issue should be closed by https://github.com/ceLoFaN/hidenseek-csgo/pull/69.
Thanks @Kailo97 !
