### ISSUE TITLE
Add penalties for Ts who suicide in Respawn Mode

### ISSUE THREAD

**Issue by ceLoFaN** [ceLoFaN/hidenseek-csgo#7]
Penalties should stack. A formula should be used to calculate the respawn time penalty based on a number of stacks. 
Example: 3 * (x ^ 2) + 2 * x, where x represents the number of stacks. This gives 5s for 1 stack, 16s for 2 stacks, 33s for 3 stacks.
Stacks should be persistent, even if a player reconnects.
Stacks are removed, one at a time, each time the player dies normally (as a T) or each time it kills an enemy (as a CT), except for the first stack which takes 2 times to remove.

Also if there is room, the T will be sent to the CT team.

**Comment by Kailo97** [comment]
With 0.7 multiplier i got (rounded)
0 1
1 2
2 3
2 4
3 5
4 6
4 7
5 8
6 9
6 10
7 11
8 12
9 13
9 14
10 15
11 16
11 17
12 18
13 19
13 20

**Comment by ceLoFaN** [comment]
Is that the CT : T players ratio? Can you explain how you got this a bit more clearly? Also this might be the wrong issue.
