### ISSUE TITLE
PLugins doesn't work ?

### ISSUE THREAD

**Issue by jffz** [ceLoFaN/hidenseek-csgo#70]
Thanks for your update, i've been able to compile but the plugin won't launch :
Load error: Native "DataPack.WriteCell" was not found

**Comment by Kailo97** [comment]
I tested with SM 1.7, it works correctly. Send your config.

**Comment by jffz** [comment]
I also use 1.7
 SourceMod Version: 1.7.3-dev+5265

No specific config, i've just compiled and put the smx in my plugins folder

2015-12-02 17:10 GMT+01:00 Maxim Telezhenko <notifications@github.com>:

**Comment by Kailo97** [comment]
Try to do full update: server, metamod, sourcemod. I don't see another way to help you, it not a HNS plugin issue. I think closed.

**Comment by jffz** [comment]
Still not working with sm 1.7 / 1.8, any other plugin is working without
issue.

2015-12-02 17:23 GMT+01:00 Maxim Telezhenko <notifications@github.com>:

**Comment by ceLoFaN** [comment]
https://forums.alliedmods.net/showpost.php?s=d9c03e8eeb24a9109ff77b61e65eb12b&p=2277228&postcount=7
https://forums.alliedmods.net/showpost.php?s=d9c03e8eeb24a9109ff77b61e65eb12b&p=2219836&postcount=6

This is probably not a plugin issue. Make sure you installed the right version of SourceMod. If you're 100% you did it right, you might want to file a bug: https://bugs.alliedmods.net/
