### ISSUE TITLE
Stuck Frozen Cant Move Must Bhop

### ISSUE THREAD

**Issue by HNSscripter** [ceLoFaN/hidenseek-csgo#80]
So i have tried tons of stuff to fix, basically i just installed the gamemode and when i spawn in i cant move (neither can the bots) but we shift walk forward and we have to bhop to be able to move. once we start bhopping and get speed we move forward faster. Fix? Anybody else receiving This issue? Help Please, Thanks!

-Scripter

**Comment by Kailo97** [comment]
I have no idea why this may happen.

> i just installed the gamemode

Do you have pure server only with HNS plugin? What plugin version?

**Comment by HNSscripter** [comment]
i Have the most recent version of HidenSeek Chasemod, heres the link:
https://github.com/ceLoFaN/hidenseek-csgo/releases/tag/v2.0.0-beta4

**Comment by HNSscripter** [comment]
I am going to try to uninstall it and re-install all plugins and ill get back to you in a bit

**Comment by HNSscripter** [comment]
Do i download the source code or the zip file from it? Or both?

**Comment by Kailo97** [comment]
Zip = all files from repo including source files.

**Comment by HNSscripter** [comment]
I have fixed the problem. i deleted the server files and re-installed and got the plugin functioning, im guessing it was a problem with the server.cfg or something.
