### ISSUE TITLE
Teambalance problems with certain server population

### ISSUE THREAD

**Issue by wul4** [ceLoFaN/hidenseek-csgo#83]
Releases affected: beta3->

In DM-mode, when there are 5+ players on the server, CT's who die (falldmg) get automatically swapped over to terrorist team. 
beta2 and earlier seem to not have this bug.

Changing teambalance and limitteams did not fix the problem. (even when removed forcing them from the plugin and compiled)

**Comment by wul4** [comment]
Fixed it by editing and recompiling beta4 release. The problem was caused by teambalancing on rows 1722-1728.

**Comment by ceLoFaN** [comment]
Hey @wul4,
Glad to hear you worked it out. Care to submit a Pull Request?
